### ISSUE TITLE
Update to latest FontAwesome script

### ISSUE THREAD

**Issue by stanimirmihov** [j-gardner/arconix-shortcodes#43]
Hello and thanks for reading.

I installed the Acronix shortcodes plugin for wordpress, but I can't see how to use them. 

I have used shortcode plugins before through the wordpress editor while I write a new post.

Screenshot: http://i.share.pho.to/d1337755_o.png

Thanks in advance for any answer.

**Comment by j-gardner** [comment]
Thanks for using my plugin. I don't have a button on the editor to add shortcodes, you'd type them directly into the editor. You can get a list of the shortcodes themselves and the various parameters they accept here: http://docs.arconixpc.com/plugins/arconix-shortcodes/shortcode-reference/

**Comment by stanimirmihov** [comment]
Thank u for the quick reply!

**Comment by stanimirmihov** [comment]
Where I can see al the shortcodes with images/screenshots (how they look)?

**Comment by j-gardner** [comment]
http://demo.arconixpc.com/arconix-shortcodes/

**Comment by stanimirmihov** [comment]
Last question. I want to use the "This is the new Tip box" (yellow) from the examples, but in the icon list there is no tip box or anything related to it. Suggestions?

**Comment by stanimirmihov** [comment]
All icons are listed in this guide and I want to replicate it if possible. If someone can give me a hand I could send paypal donation.

Thanks in advance.

Guide: http://backlinko.com/ecommerce-seo/comment-page-19#comment-75952

Icons: 
http://fontawesome.io/icon/question-circle-o/ - question - orange
http://fontawesome.io/icon/check-circle-o/ - check circle- light green
http://fontawesome.io/icon/lightbulb-o/ - lightbulb
http://fontawesome.io/icon/times-circle-o/ - times - red
http://fontawesome.io/icon/exclamation-circle/ - exclamation - red

**Comment by j-gardner** [comment]
Assuming you're using the box shortcode:

`
[box icon="fa-question-circle-o" color=blue]
bacon ipsum
[/box]
`
I tried it myself and I noticed it doesn't work. That icon must be a newer icon that isn't supported in the version I'm loading with the plugin. I'll get that version updated for you this weekend.

**Comment by stanimirmihov** [comment]
j-gardner, thanks a lot! Did you see the other icons? 5 total

**Comment by j-gardner** [comment]
Once I update the plugin to pull the new script version they'll all work because the icons all work the same way; just the name changes.

**Comment by stanimirmihov** [comment]
Thanks again. I tried all and [box icon="fa-exclamation-circle" color=red] works well, other work without icons. :)

Greetings

**Comment by stanimirmihov** [comment]
Hello. Did you mean there will be plugin update this saturday/sunday?

**Comment by j-gardner** [comment]
correct. I'm hoping to have the update pushed out tonight.

**Comment by stanimirmihov** [comment]
Hello. I updated the plugin, but it's still not working.

You can check my latest article in preview mode where I try to test some features.

https://stanimirmihov.com/?p=2137&preview=1&_ppp=dac45d7bbf

I use "[box icon="lightbulb-о" color=lblue]Съвети[/box] 

You can search in the article for " da se testvat " and it will go to this line.

**Comment by j-gardner** [comment]
put "fa-" in front of "lightbulb-o":
`
[box icon=fa-lightbulb-o color=lblue]
`

**Comment by stanimirmihov** [comment]
Working just fine. Thank u!
